// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// TO GET YOUR ACTUAL FIREBASE CONFIG:
/// 1. Go to https://console.firebase.google.com/
/// 2. Select your "exerciselist" project
/// 3. Click the gear icon (Project Settings)
/// 4. Scroll down to "Your apps" section
/// 5. If you don't have a web app, click "Add app" and select Web
/// 6. Copy the firebaseConfig values and replace the placeholders below
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaUt7NFytu6QHUyI7-lOJYY7_Xxbmmm8',
    appId: '1:61388203199:web:4c9b99421a4157b658520a',
    messagingSenderId: '61388203199',
    projectId: 'exerciselist-da299',
    authDomain: 'exerciselist-da299.firebaseapp.com',
    storageBucket: 'exerciselist-da299.firebasestorage.app',
    measurementId: 'G-2VXD7NH1JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLONZn1TlWkwbm29JGDomjEX0wKFl-TY',
    appId: '1:61388203199:android:58a7a902c57c944e58520a',
    messagingSenderId: '61388203199',
    projectId: 'exerciselist-da299',
    storageBucket: 'exerciselist-da299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8nCuZn0HRw1fw7MnyCPXxedyWaxGOkrw',
    appId: '1:61388203199:ios:faaf7ec68caf10d758520a',
    messagingSenderId: '61388203199',
    projectId: 'exerciselist-da299',
    storageBucket: 'exerciselist-da299.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8nCuZn0HRw1fw7MnyCPXxedyWaxGOkrw',
    appId: '1:61388203199:ios:faaf7ec68caf10d758520a',
    messagingSenderId: '61388203199',
    projectId: 'exerciselist-da299',
    storageBucket: 'exerciselist-da299.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRaUt7NFytu6QHUyI7-lOJYY7_Xxbmmm8',
    appId: '1:61388203199:web:8dda3b72975e5cee58520a',
    messagingSenderId: '61388203199',
    projectId: 'exerciselist-da299',
    authDomain: 'exerciselist-da299.firebaseapp.com',
    storageBucket: 'exerciselist-da299.firebasestorage.app',
    measurementId: 'G-H4WXHK7D0L',
  );

}